---
- hosts: cluster
  remote_user: root
  become: true
  tasks:
    - name: create devops user
      user:
        name: ansible
        shell: /bin/bash
        #groups: sudo
        append: yes
        password: "{{ 'vagrant' | password_hash('sha512') }}"
      become: yes

    - name: Add devops user to the sudoers
      copy:
        dest: "/etc/sudoers.d/ansible"
        content: "ansible  ALL=(ALL)  NOPASSWD: ALL"
      become: yes
    
      
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      openssh_keypair:
        owner: ansible
        group: ansible
        path: /home/ansible/.ssh/id_rsa
        type: rsa
        state: present
      delegate_to: localhost
      become: no
         
    - name: Deploy SSH Key
      authorized_key: 
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
      