  - name: Start patroni on the  nodes
    become: yes
    systemd:
      name: patroni
      state: started
      enabled: yes

  - name: Find PostgreSQL data folder
    become: yes
    find:
      paths: /var/lib/pgsql/15/
      file_type: directory
      patterns: data*
    register: found_data_folder


  - name: Rename PostgreSQL data folder
    become: yes
    command: mv "{{ found_data_folder.files[0].path }}" /var/lib/pgsql/15/data_old
    when: found_data_folder.matched > 0

  - name: again rename data folder
    become: yes
    command: mv /var/lib/pgsql/15/data_old /var/lib/pgsql/15/data
    when: found_data_folder.matched > 0